### ISSUE TITLE
Version on Hackage is broken due to conflicting instances with math-functions

### ISSUE THREAD

**Issue by gcross** [Shimuuar/monoid-statistics#1]
At the moment it is not possible to use this package with the latest LTS in Stackage because monoid-statistics defines orphan instances of the Monoid class for KahanSum and KBNSum that clash with the (new) instances in math-functions.  Fortunately, it looks like you have already fixed this in HEAD, so resolving the problem should be as simple as uploading the current version to Hackage.

**Comment by o1lo01ol1o** [comment]
ping @Shimuuar

**Comment by Shimuuar** [comment]
Right now master is in half broken state. I made release 1.0.1.0 which is slightly patched 1.0.0.0 to support math-functions-0.3.* and newer GHC
